import { randomBytes, createCipheriv, createDecipheriv } from "node:crypto";

/**
 * Encrypts/decrypts BYOK provider API keys (Decision 24). The master key
 * lives only in AES_MASTER_KEY (container env, generated by
 * scripts/generate-aes-key.sh) — never in Postgres. Decrypt only
 * server-side, immediately before calling the provider; never send
 * ciphertext OR plaintext back to the client.
 */

const ALGORITHM = "aes-256-gcm";

function getMasterKey(): Buffer {
  const b64 = process.env.AES_MASTER_KEY;
  if (!b64) throw new Error("AES_MASTER_KEY is not set");
  const key = Buffer.from(b64, "base64");
  if (key.length !== 32) {
    throw new Error(`AES_MASTER_KEY must decode to 32 bytes, got ${key.length}`);
  }
  return key;
}

/** Returns a single base64 string: iv(12) || authTag(16) || ciphertext. */
export function encryptApiKey(plaintext: string): string {
  const key = getMasterKey();
  const iv = randomBytes(12);
  const cipher = createCipheriv(ALGORITHM, key, iv);
  const ciphertext = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);
  const authTag = cipher.getAuthTag();
  return Buffer.concat([iv, authTag, ciphertext]).toString("base64");
}

export function decryptApiKey(blob: string): string {
  const key = getMasterKey();
  const buf = Buffer.from(blob, "base64");
  const iv = buf.subarray(0, 12);
  const authTag = buf.subarray(12, 28);
  const ciphertext = buf.subarray(28);
  const decipher = createDecipheriv(ALGORITHM, key, iv);
  decipher.setAuthTag(authTag);
  return Buffer.concat([decipher.update(ciphertext), decipher.final()]).toString("utf8");
}

/** For settings forms: never echo a real key back, only whether one is set. */
export function maskApiKey(encrypted: string | null): string | null {
  return encrypted ? "••••••••" : null;
}
